[package]
name = "Daemos"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
docker-api = "0.14.0"
mysql = "26.0.0"
tokio = { version = "1.46.1", features = ["rt-multi-thread", "macros"] }
